### ISSUE TITLE
Update inline-var to find identifier in current line if cursor not on it

### ISSUE THREAD

**Issue by teddylear** [ThePrimeagen/refactoring.nvim#175]
As noted in [this PR](https://github.com/ThePrimeagen/refactoring.nvim/pull/174), we should make inline-var more user friendly by finding the identifier in the current line if the cursor is not on it. Currently we have this error out to make this more obvious.

**Comment by pranavrao145** [comment]
I was thinking about how to approach this one. Either we can try to find the identifier in the current line (runs into problems with multiple declarations in a line such as in #207), or we can try to find the first identifier in the current visual selection. I think the second one is better simply because the problem is that the *cursor's* not in the right place; the user will visual select the variable they want to inline no matter what. What do you think about this @teddylear?

**Comment by teddylear** [comment]
@pranavrao145 What are your thoughts on this, in the case of one identifier we select the first one present in line. Then if there are two (or more) identifiers in the line we add a prompt listing each identifier in the line and the user picks which one we want to inline. Thought I'm not sure how this would work with the current implementation we have...

Else we have to go with the second approach (which I'm fine with as well), but I think the first option for most cases is a better user experience.

**Comment by pranavrao145** [comment]
I like that idea - a prompt would be best. I will try to get working on this sometime during the week and let you know how it goes!

**Comment by pranavrao145** [comment]
This is solved with #211 - can we close this issue?

**Comment by teddylear** [comment]
@pranavrao145 I'll close, can you make an issue for the other part of the PR we discussed so we can track it? That being removing the initial declaration when there are multiple declaration on the same line. Else I can make the issue.
