### ISSUE TITLE
Export function to file error

### ISSUE THREAD

**Issue by chaozwn** [ThePrimeagen/refactoring.nvim#373]
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = InternalError, message = "Request textDocument/foldingRange failed with message: The document should be opened for foldingRanges', file: /Users/mac/reactProject/wenjuan-fe/src/demo.ts" fn fn.

![image](https://user-images.githubusercontent.com/51357674/236853297-49c792f7-6d40-4b3a-a615-64f3436cea31.png)

**Comment by TheLeoP** [comment]
This happens because of a conflict with nvim-ufo (or at least in my config, that's the reason). ufo asumes that a file exists before it's filetype is set, but this plugin first sets the filetype and then saves the newly created file. The fix is simple, [here](https://github.com/ThePrimeagen/refactoring.nvim/blob/47a1716a9020c0093a1c8af36c3f9434dae62bbd/lua/refactoring/tasks/create_file.lua#L12) the filetype should be set after the file creation (swap lines 12 and 13). I'm currently waiting for #372 to get merged/receive some feedback to open a new PR to address this and other issues.

**Comment by chaozwn** [comment]
> This happens because of a conflict with nvim-ufo (or at least in my config, that's the reason). ufo asumes that a file exists before it's filetype is set, but this plugin first sets the filetype and then saves the newly created file. The fix is simple, [here](https://github.com/ThePrimeagen/refactoring.nvim/blob/47a1716a9020c0093a1c8af36c3f9434dae62bbd/lua/refactoring/tasks/create_file.lua#L12) the filetype should be set after the file creation (swap lines 12 and 13). I'm currently waiting for #372 to get merged/receive some feedback to open a new PR to address this and other issues.

How do I feel that the author is no longer in maintenance? It’s been two weeks and hasn’t been merged yet.
