### ISSUE TITLE
Why is nightly nvim a requirement?

### ISSUE THREAD

**Issue by vitarb** [ThePrimeagen/refactoring.nvim#377]
It's been a while since this plugin has been introduced but it still requires nvim nightly build.
I'm curious what is the reason for that, and how is that possible that changes from nightly *still* didn't make it into the release for multiple years now? Is there any issue tracking this on the nvim's side that we can follow and +1 it?

**Comment by teddylear** [comment]
@vitarb Currently we require nightly because we don't want to maintain various versions of the plugin and rather fix foreward as we haven't hit too many breaking changes (aside from upstream treesitter changes, but we can't do anything about that). Are there features from nightly that you want to see in the plugin? There would be no issue on the nvim side as this is an external plugin to the neovim project.
