### ISSUE TITLE
[Question] Get node references/usages

### ISSUE THREAD

**Issue by wuilliam321** [ThePrimeagen/refactoring.nvim#378]
Hi, I'm working on this feature https://github.com/ThePrimeagen/refactoring.nvim/issues/366, and I'm trying to get all the references of a function:

```go
package main

import "fmt"

func extracted() {
	fmt.Errorf("test")
}

func simple_function() {
      ->extracted()      // here is the cusor
	fmt.Println("test2")
	fmt.Println("test3")
	fmt.Println("test4")
	fmt.Println("test5")
}
```
I'm running a very simple test to get all the references of `extracted()` in order to replace all the occurrences with `fmt.Errorf("test")`

```lua
    local node_at_point = ts.get_node_at_cursor()
    local definition, scope = ts_locals.find_definition(node_at_point, bufnr)

    -- This references table is completely empty
    local references =
        ts.find_references(definition, scope, bufnr, definition)

    -- This works nicely, but deletes the call_expression not the function_declaration
    table.insert(
        text_edits,
        lsp_utils.delete_text(Region:from_node(node_at_point, bufnr))
    )
```
I also used `ts_locals.find_usages(node_at_point, scope, bufnr)` to get all the "usages" but the function declaration is not retrieved, so I'm not able to get the right node and abstract the node_text from it.

Note:
This is the actual code I have:
```lua
local function inline_func_setup(refactor, bufnr)
    local node_at_point = ts.get_node_at_cursor()
    print("INLINE_FUNC_DEBUG node_at_point")
    print(dumpcode(node_at_point))
    print(dumpcode(node_at_point:parent()))
    print("")

    local definition, scope = ts_locals.find_definition(node_at_point, bufnr)
    print("INLINE_FUNC_DEBUG definition")
    print(dumpcode(definition))
    print(dumpcode(definition:parent()))
    print("")

    local references = ts.find_references(definition, scope, bufnr, definition)
    print("INLINE_FUNC_DEBUG references")
    print(dumpcode(references))
    print("")

    local text_edits = {}

    -- TODO: find and delete the function declaration
    -- table.insert(
    --     text_edits,
    --     lsp_utils.delete_text(Region:from_node(node_at_point, bufnr))
    -- )

    print("INLINE_FUNC_DEBUG running refactoring")
    local lsp_range = ts_utils2.node_to_lsp_range(node_at_point:parent())
    local text_edit = { range = lsp_range, newText = 'fmt.Errorf("test")' }
    table.insert(text_edits, text_edit)

    refactor.text_edits = text_edits
end
```
And this is the test output:
```
from inline_func	
INLINE_FUNC_DEBUG node_at_point	
{ [1] = extracted,} 	
{ [1] = extracted(),} 	
	
INLINE_FUNC_DEBUG definition	
{ [1] = extracted,} 	
{ [1] = extracted(),} 	
	
INLINE_FUNC_DEBUG references	
{ } 	
	
INLINE_FUNC_DEBUG running refactoring	
Fail	||	Refactoring Refactoring: refactor/115/go/simple-function/inline_func.start.go	
            ../plenary.nvim/lua/plenary/async/util.lua:37: Blocking on future timed out or was interrupted.
            ...refactoring.nvim/lua/refactoring/tests/refactor_spec.lua:226: Expected objects to be the same.
            Passed in:
            (table: 0x41229468) {
              [1] = 'package main'
              [2] = ''
              [3] = 'import "fmt"'
              [4] = ''
             *[5] = 'func extracted() {'
              [6] = '	fmt.Errorf("test")'
              [7] = '}'
              [8] = ''
              [9] = 'func simple_function() {'
              [10] = '	fmt.Errorf("test")'
              [11] = '	fmt.Println("test2")'
              [12] = '	fmt.Println("test3")'
              [13] = '	fmt.Println("test4")'
              [14] = '	fmt.Println("test5")'
              [15] = '}' }
            Expected:
            (table: 0x40458300) {
              [1] = 'package main'
              [2] = ''
              [3] = 'import "fmt"'
              [4] = ''
             *[5] = ''
              [6] = ''
              [7] = 'func simple_function() {'
              [8] = '	fmt.Errorf("test")'
              [9] = '	fmt.Println("test2")'
              [10] = '	fmt.Println("test3")'
              [11] = '	fmt.Println("test4")'
              [12] = '	fmt.Println("test5")'
              [13] = '}' }
```

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/236566/59e90e6a-8617-4817-aaa7-bd56f2e76c38)

Note: ChatGPT is not well trained with nvim-treesitter hehehe

**Comment by wuilliam321** [comment]
@TheLeoP any idea on your side?

**Comment by wuilliam321** [comment]
this is the PR I'm working in: https://github.com/ThePrimeagen/refactoring.nvim/pull/379

**Comment by TheLeoP** [comment]
@wuilliam321 the reason why `find_definition` doesn't work as you expect is because you aren't using it as `nvim-treesitter` intended. `nvim-treesitter` has a reference to all the definitions on a buffer on a table which keys are both the text and the range of the node. So, if you pass it a nodes, it will check if it's on that table (remember, same range and same text) and, if yes, return it; if no, they will return the same node. (If you were to use `find_definition` with your cursor over the function definition, it will work as you expected, but since you are using a node with the same text and a different range, it does not work).

The reason why `find_usages` isn't working as you expected is because it uses `find_definition` under the hood.

I don't think it's necesary to add the function `find_declaration` if we treat this refactor in the same way as `123` (the cursor has to be on top of the definition of the function/variable to work).

Besides that, your PR seems to be working for your test case. I would sugget replacing the calls to `ts_utils.get_node_text(value, bufnr)[1]` with `vim.treesitter.get_node_text(value, bufnr)` since the first one is deprecated (you should note that the first one returns a table and the second one doesn't, so there is no need to select the first value of it with `[1]` after doing this change).

Finally, on line 89 of `115.lua` you are only saving the last line of the function body, you should concatenate all lines using newlines to separate them.

**Comment by wuilliam321** [comment]
I left the find_declaration for now, because it is working. I'm gonna open another ticket, I need to get the `argument_list` of a `call_expression`
