### ISSUE TITLE
[Question]  Duplicated code in `refactor.ts:get_function_body(node)`

### ISSUE THREAD

**Issue by wuilliam321** [ThePrimeagen/refactoring.nvim#387]
I'm working on this: https://github.com/ThePrimeagen/refactoring.nvim/issues/366

And I have a `bug` maybe when trying to use this:
```lua
refactor.ts:get_function_body(node)
```
Let me add some context:
This is a test `inline_func.start.go`:
```go
package main

import "fmt"

type Message struct{
    value int
}
type Response struct{}

func extracted(a Message) (Response, error) {
    r := Response{}

    if a.value == 1 {
        // return r, nil
    }

    if a.value == 2 {
        if a.value > 2 {
            // return r, fmt.Errorf("Error")
        }
        // return Response{}, nil
    }

    if a.value == 3 {
        a.value = 5
    }

    return r, nil
}

func simple_function() {
    x, err := extracted(Message{value: 2})
    if err != nil {
        panic(err)
    }
    fmt.Println(x)
}
```
and this is the `inline_func.expected.go`:
```go
package main

import "fmt"

type Message struct{
    value int
}
type Response struct{}



func simple_function() {
    a := Message{value: 2}
    r := Response{}
    if a.value == 1 {
        // return r, nil
    }
    if a.value == 2 {
        if a.value > 2 {
            // return r, fmt.Errorf("Error")
        }
        // return Response{}, nil
    }
    if a.value == 3 {
        a.value = 5
    }
    x, err := r, nil
    if err != nil {
        panic(err)
    }
    fmt.Println(x)
}
```
But the `actual_output` code is this:
```go
package main

import "fmt"

type Message struct{
    value int
}
type Response struct{}



func simple_function() {
    a := Message{value: 2}
    r := Response{}
    if a.value == 1 {
        // return r, nil
    }
    // return r, nil
    if a.value == 2 {
        if a.value > 2 {
            // return r, fmt.Errorf("Error")
        }
        // return Response{}, nil
    }
    if a.value > 2 {
            // return r, fmt.Errorf("Error")
        }
    // return r, fmt.Errorf("Error")
    // return Response{}, nil
    if a.value == 3 {
        a.value = 5
    }
    a.value = 5
    x, err := r, nil
    if err != nil {
        panic(err)
    }
    fmt.Println(x)
}

```

Here you can see the difference between them:
```diff
--- actual_output	2023-05-31 22:04:17.022814341 -0300
+++ zapato/inline_func.expected.go	2023-05-31 19:58:37.931988551 -0300
@@ -15,22 +15,15 @@
     if a.value == 1 {
         // return r, nil
     }
-    // return r, nil
     if a.value == 2 {
         if a.value > 2 {
             // return r, fmt.Errorf("Error")
         }
         // return Response{}, nil
     }
-    if a.value > 2 {
-            // return r, fmt.Errorf("Error")
-        }
-    // return r, fmt.Errorf("Error")
-    // return Response{}, nil
     if a.value == 3 {
         a.value = 5
     }
-    a.value = 5
     x, err := r, nil
     if err != nil {
         panic(err)
```

this is the output of :
```lua
    local sentences = refactor.ts:get_function_body(function_declaration)
    for _, sentence in ipairs(sentences) do
        print(vim.treesitter.get_node_text(sentence, bufnr))
    end

```
is:
```txt
body	
r := Response{}	
if a.value == 1 {
        // return r, nil
    }	
// return r, nil	
if a.value == 2 {
        if a.value > 2 {
            // return r, fmt.Errorf("Error")
        }
        // return Response{}, nil
    }	
if a.value > 2 {
            // return r, fmt.Errorf("Error")
        }	
// return r, fmt.Errorf("Error")	
// return Response{}, nil	
if a.value == 3 {
        a.value = 5
    }	
a.value = 5	
return r, nil	
```
There are in fact, some duplicated code/nodes. Are they expected to be duplicated? How can I get the whole function declaration body?

**Comment by wuilliam321** [comment]
@TheLeoP maybe you can help me (again xD)

**Comment by TheLeoP** [comment]
@wuilliam321 

The only place where we currently use `ts:get_function_body(scope)` is for 106 (extract_block). There, it is used like this

```lua
    local block_first_child = refactor.ts:get_function_body(scope)[1]
    local block_last_child = block_first_child -- starting off here, we're going to find it manually

    -- we have to find the last direct sibling manually because raw queries
    -- pick up nested children nodes as well
    while block_last_child:next_named_sibling() do
        block_last_child = block_last_child:next_named_sibling()
    end
```

I wasn't sure why, so I checked the captures for `function_body` for some languages. Turns out that there are two types of treesitter parsers in this regard: the ones with a node for a whole block of code (the body of a function, of an if statement, etc), and the ones without such node. Go is the first type. If you check out `treesitter/langs/go.lua`, go will see that the captures that go uses is `(block (_) @tmp_capture)`. In your case, this captures the following nodes:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/53507599/29f56818-183a-46e0-8d34-4678d2c95529)

It isn't evident at first, but this captures the body of the function as well as the body of each if statement, for statement, etc. 

An example of the second type of treesitter parser is typescript. The capture used for it is `(statement_block (_) @tmp_capture)` and captures the following nodes:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/53507599/38412c09-583c-428a-b104-1729be1fbd66)

It should be noted that there is no single capture for the whole body of the function. Instead, it's capturing each of the lines of the function separately (and it does the same with the lines inside the for statement, just like in go).

So, now the code of extract_block makes sense. The first node returned by `ts:get_function_body(scope)` may be the whole block of the function (like in go) or the first line of the function (like in typescript). So, to get the body of the function, you have to need something like the following:

```lua
    local block_first_child = refactor.ts:get_function_body(scope)[1]
    local block_last_child = block_first_child -- starting off here, we're going to find it manually

    -- we have to find the last direct sibling manually because raw queries
    -- pick up nested children nodes as well
    while block_last_child:next_named_sibling() do
        block_last_child = block_last_child:next_named_sibling()
    end

    local first_line_region = Region:from_node(block_first_child)
    local last_line_region = Region:from_node(block_last_child)

    -- update the region and its node with the block scope found
    region = Region:from_values(
        refactor.bufnr,
        first_line_region.start_row,
        -- The Tresitter delimited region never includes the blank spaces
        -- before the first line which causes problems with indentation.
        1,
        last_line_region.end_row,
        last_line_region.end_col
    )

    local function_body = refactor.region:get_text()
```

This code is copy pasted from 106; so, if you are reusing it, it would make sense to extract it to a general function (?). It could be tricky because the last line is in a different task in the case of 106 (`extract_block_setup` selects the correct region and `extract_setup` gets the text from the selected region. At lest the first part could be extracted to a common function.

**Comment by wuilliam321** [comment]
I found a way to solve it, but I have a lot more work, because this code ends up totally un-indented hehe, and the issue may be in the other implementations, so I need to try to reproduce it.
