### ISSUE TITLE
Several issues with PHP

### ISSUE THREAD

**Issue by calebdw** [ThePrimeagen/refactoring.nvim#389]
Hello!

I've experienced several issues with this plugin in PHP:

1. `Extract Function` doesn't include `$` in variables names:
    ```php
    public function testing (
    
    ) {
                $schedules = $this->station->schedules()
                ->forDate($this->date)
                ->orderByDescNullsLast('start_date')
                ->orderByNullsLast('end_date')
                ->orderByNullsLast('week_days')
                ->orderByDesc('id')
                ->get();
            return schedules;
    }
    // later on
    schedules = $this->testing(); // here was where I extracted the code block above
    ```
2. `Extract Variable` either errors with
    1. Extract var unable to determine its containing statement within the block scope
    2. block_scope is nil! Something went wrong
 3. `Inline Variable` fails with:
     
![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/4176520/d71c020b-3502-4a13-af04-57abd6cf766d)

### Config
Using Lazy.nvim 

```lua
return {
  'ThePrimeagen/refactoring.nvim',
  opts = {},
  config = function(_, opts)
    local refactoring = require('refactoring')
    local map = require('user.util').map

    refactoring.setup(opts)

    map({ 'v' }, '<leader>rr', refactoring.select_refactor, { noremap = true })
  end,
  dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-treesitter/nvim-treesitter',
  },
}
```

**Comment by TheLeoP** [comment]
Could you provide the code that you used for Extract variable and Inline variable?

**Comment by CalebDW** [comment]
Sure, here's a snippet (although I imagine that you could try any php code...unless I'm just using the plugin wrong)


```php
<?php

namespace Refactoring;

class Testing
{
    public function cleanAndFormatCurrency(mixed $currency): string
    {
        $cleanedCurrency = preg_replace('/[^0-9.]/', '', $currency);

        return number_format((float) $cleanedCurrency, 2);
    }
}
```

- Visually selecting the regex `'/[^0-9.]/'` string and attempting to extract variable yields the block scope error
- Visually selecting the first `$cleanedCurrency` and attempting to inline the variable yields the coroutine error

**Comment by TheLeoP** [comment]
> Extract Function doesn't include $ in variables names

I know why this happens, I'll try to solve it.

> Visually selecting the regex '/[^0-9.]/' string and attempting to extract variable yields the block scope error

This actually works fine for me. Are you on the latest version of the plugin? If yes, a minimal reproduction may be needed so I can solve this one.

> Visually selecting the first $cleanedCurrency and attempting to inline the variable yields the coroutine error

I can reproduce this one too, so I'll look into it

**Comment by TheLeoP** [comment]
I think I have solved issued `1` and `3`. Could you try [my changes](https://github.com/theleop/refactoring.nvim) to verify?

**Comment by CalebDW** [comment]
`3` is working, thanks!

`1` results in the following structure when I try to extract function:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/4176520/324c7ed8-6772-4336-a885-60c41ea59a04)

`2` briefly did something, but when I visually selected the regex string it results in:

```php
        $test = /[^0-9.]/;
        $cleanedCurrency = preg_replace('$test', '', $currency);
```

**Comment by TheLeoP** [comment]
I think 1 should be working know. Could you try my changes again?

> 2 when I visually selected the regex string it results in:

You are selecting the whole string, right? That is, including the `'`. I can reproduce this behaviour only if I select the content of the string without the single quotes (`/[^0-9.]/`).

**Comment by CalebDW** [comment]
`1` does a little better but still messes up brackets

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/4176520/424ce465-38d3-4931-a859-1aef4af8e2ec)

> You are selecting the whole string, right? That is, including the '. I can reproduce this behaviour only if I select the content of the string without the single quotes (/[^0-9.]/).

I am selecting the entire string.... the weird thing is I tried it and it worked when I was in my dotfile repo, however, it still yields the following two errors when I am inside my primary work repo (which is weird....). A language server wouldn't interfere with this plugin right (it's just using treesitter?)?

1. Extract var unable to determine its containing statement within the block scope
2. block_scope is nil! Something went wrong


 What's the difference between Extract `Block` vs `Function`?

**Comment by TheLeoP** [comment]
> 1 does a little better but still messes up brackets

Indentation in kinda hard to do correctly right now. Ideally, if you have a formatter set up, it should handle this. I just pushed some updated (because it turns out that the PHP support wasn't fully configured, so some things where working kind of weirdly).

> A language server wouldn't interfere with this plugin right (it's just using treesitter?)?

Currently, we don't use language servers for anything, just treesitter. What could be happening is that the code on your work repo is different from your test code and that's why it fails.

The plugin handles things like what should be indented or what should be considered a scope based on treesitter. So, in javascript for example, if you use an arrow function instead of a regular function, they may produce different results if one is in our default configuration and the other isn't. So. if you could make a minimal example of the code where the plugin fails, it would help us determine what could be causing the issue.

> Extract var unable to determine its containing statement within the block scope

This usually means that we haven't configured that specific scope into the plugin yet. Before my last push, the plugin was only considering classes and methods as scopes (now it also considers functions). That may be why you found this error. Could you try once more?

> What's the difference between Extract Block vs Function?

I'm not 100% sure on their differences (I haven't touch all of that specific code on the codebase). But, from a functional point of view:
- `extract block` doesn't require a visual selection and extracts all the code in the current scope
- `extract function` requires a visual selection and extracts the visually selected code (handling return values and which parameters should be passes to the function)

**Comment by CalebDW** [comment]
By messing up the brackets I mean that the original function is left without any brackets at all

> Currently, we don't use language servers for anything, just treesitter. What could be happening is that the code on your work repo is different from your test code and that's why it fails.

No, I literally copied the test code above (as `test.php`) into my work repo, that's the only difference between the file working in my dotfile repo. The work repo is a Laravel project so has phpactor running as a language server in the background as well as using PHPStan but I can't imagine that messing with the plugin and Treesitter is scoped to the file so the project shouldn't matter

**Comment by TheLeoP** [comment]
> By messing up the brackets I mean that the original function is left without any brackets at all

Sorry, I missuderstood you. It looks like extract_block in particular isn't working as expected. I'll look into into

> No, I literally copied the test code above (as test.php) into my work repo, that's the only difference between the file working in my dotfile repo. The work repo is a Laravel project so has phpactor running as a language server in the background as well as using PHPStan but I can't imagine that messing with the plugin and Treesitter is scoped to the file so the project shouldn't matter

That's really weird. I have no idea about why it may be happening.

**Comment by TheLeoP** [comment]
@CalebDW could you try my changes once more?

**Comment by CalebDW** [comment]
`Extract block` still has messed up brackets, but is using `$this->` as it should:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/4176520/9c478832-e8bb-4254-89ae-f053c8844068)


Visually selecting the function body and using `Extract Function`  gives:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/4176520/51c58318-f8f8-413c-982c-ec5ca416fbed)


Visually selecting the regex string and using `Extract Variable` extracts the entire function call:

![image](https://github.com/ThePrimeagen/refactoring.nvim/assets/4176520/9f86b6d5-7824-451e-9a84-6f6db5f2adbb)

**Comment by TheLeoP** [comment]
> Extract block still has messed up brackets, but is using $this-> as it should:

Are you using the changes I pushed 30 minutes ago? I can no longer replicate this behaviour.

> Visually selecting the function body and using Extract Function gives:

Probably you are setting the mappings incorrectly. The visual selection range gets set after exiting visual mode, that's why the mappings in the README use `<esc>`. If not, how are you setting your mappings?

> Visually selecting the regex string and using Extract Variable extracts the entire function call:

Yeah, this is the mapping problem again. The plugin is using your last selection (the one that you did for extract function) because the markers for the visual selection aren't being updated

**Comment by CalebDW** [comment]
I had updated the plugins, but I just tried and the Block/Functions work!

I haven't setup individual mappings for the different operations, I've just been using the selection menu:

```lua
    map({ 'v' }, '<leader>rr', refactoring.select_refactor, { noremap = true })
```

where `map` is just a wrapper around `vim.keymap.set` that sets some defaults

**Comment by TheLeoP** [comment]
> I had updated the plugins, but I just tried and the Block/Functions work!

Yay :D

> I haven't setup individual mappings for the different operations, I've just been using the selection menu:

You should create your mappings by either `<Esc><Cmd>lua call_function_here<CR>]]`, `:lua call_function_here<CR>` or, if you want to use a lua function, something like the following:

```lua
function()
  vim.cmd "normal "
  refactoring.select_refactor()
end
```

(The `` character is what Neovim sees when you pres `<esc>`).

So, your keymap shoul look like the following:

```lua
map({ "x" }, "<leader>rr", function()
  vim.cmd "normal "
  refactoring.select_refactor()
end)
```

(`nnoremap` isn't needed and `x` mode excludes selection mode)

**Comment by CalebDW** [comment]
Ah interesting, that seems to work better! I generally prefer to stick with lua instead of string vim commands

The docs should probably be updated---they have `noremap` set and don't really explain the need for `<esc>`


Thanks for the `vim.cmd('normal �')` bit, I learn something new every day!

I suppose there's not a lua function to grab the visually selected region instead of relying on `<esc>` to be pressed and the `'<,'>` registers to be populated?

**Comment by TheLeoP** [comment]
> The docs should probably be updated---they have noremap set and don't really explain the need for <esc>

Actually, those do need `noremap` because they are using strings as the RHS of the map. You are using a lua function without `expr = true`, so it's not needed.

> I suppose there's not a lua function to grab the visually selected region instead of relying on <esc> to be pressed and the '<,'> registers to be populated?

Not that I'm aware of. The most you can do is use `normal` as a function (`vim.cmd.normal(�)`)

Is this issue solved? So I can open a PR to merge the changes

**Comment by CalebDW** [comment]
Ahhh okay,  well thanks for all your help! I certainly appreciate it! You can open the PR 🙂

**Comment by TheLeoP** [comment]
No problem. I'm happy to help :D
