### ISSUE TITLE
Refactoring.nvim not work with typescript 

### ISSUE THREAD

**Issue by tuanbass** [ThePrimeagen/refactoring.nvim#404]
When trying to use the plugin with typescript, I have following error 
- Extract Function: give me the error: `Current selected region is empty, have to provide a non empty region to perform a extract func operation`. I already in Visual mode, and select line 2 and 3. 
- Extract variable: give the error : `block_scope is nil! Something went wrong`. I was in visual mode, and selected `2 + a`
- Extract Block : work well

Code test 
```typescript
function testFunc(): number {
  let a = 2;
  console.log(a);

  return 1 + 2 + a;
}

var x = testFunc();
var y = x + 3 + 4;

```

config (with LazyVim)

```lua
  {
    "ThePrimeagen/refactoring.nvim",
    opts = {},
    config = function(_, opts)
      local refactoring = require("refactoring")
      -- local map = require("user.util").map

      refactoring.setup(opts)

      vim.keymap.set({ "v", "n" }, "<leader>rr", refactoring.select_refactor, { noremap = true })
      -- vim.keymap.set("n", "s", require("substitute").operator, { noremap = true })
    end,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
  },

```

Did I make a mistake? 
The interesting part is "sometime" it works, but almost time, the error raised, especially when I have just start my nvim

**Comment by mmirus** [comment]
Ditto here. Seems like if I run one of the Ex commands, the mapping starts to work, but otherwise I get these errors.

```lua
-- Using lazy.nvim
  {
    "ThePrimeagen/refactoring.nvim",
    keys = {
      {
        "<leader>rr",
        function()
          require("refactoring").select_refactor()
        end,
        mode = { "n", "x" },
        desc = "Refactor",
      },
    },
    config = true,
    dependencies = { "nvim-lua/plenary.nvim", "nvim-treesitter/nvim-treesitter" },
  }
```

**Comment by TheLeoP** [comment]
This should be solved by [this commit](https://github.com/ThePrimeagen/refactoring.nvim/commit/85cf9cb68ae4303f4c1deaf1a2009f098664e6c8). Could you try it?

It looks like `vim.ui.select` exits visual mode without setting the visual mode marks (`<` and `>`), so we need to exit visual mode before calling it in order to set the marks.

**Comment by tuanbass** [comment]
> This should be solved by [this commit](https://github.com/ThePrimeagen/refactoring.nvim/commit/85cf9cb68ae4303f4c1deaf1a2009f098664e6c8). Could you try it?
> 
> It looks like `vim.ui.select` exits visual mode without setting the visual mode marks (`<` and `>`), so we need to exit visual mode before calling it in order to set the marks.

Thanks for the fix. 
Now "Extract function" work well 
However, a new problem raised with "Extract variable" . I tried to extract "2+a" to a variable named "temp" and here is the result.
Sure, it's not I intended to do 

```typescript
function testFunc(): number {
  let b = 1;
  let a = 2 + b;

  console.log(a);

  const temp = 1+2+a;
  return temp;
}

```

Seem there some problem when determine the VISUAL region

**Comment by TheLeoP** [comment]
That is kind of a limitation of treesitter (as far as I know). Currently, the Plugin asks Neovim for a node containing the visual selection and, because how nodes of binary operations work, the smallest node containing the visual selection may be the whole right side of the variable assignment.

I've been trying to use a different method for extract var but im currently stuck. It's posible to get the sexpression of each node in the selection (for example, a number, a `+ and an `identifier`). But, we then would need to query treesitter for each permutation of the three nodes being either siblings or two of them being siblings and one of them being part sibling of a parent node (a binary operation, for example) and thus would be exponentially more difficult for each node on the visual selection.

I would choose this issue, could you open a new one copying this other error to keep track of it?

**Comment by tuanbass** [comment]
> 

Sure. I will create new one. 
Thanks
