### ISSUE TITLE
Incorrect result of Extract Variable 

### ISSUE THREAD

**Issue by tuanbass** [ThePrimeagen/refactoring.nvim#407]
When trying to extract part of expression as variable, whole expression is extracted instead of the selected part.

Code test: 

```typescript 
function testFunc(): number {
  let a = 2;
  console.log(a);

  return 1 + 2 + a;
}

var x = testFunc();
var y = x + 3 + 4;
```

trying to export `2+a` as a new variable. The result: 

```typescript
  const temp = 1+2+a;
  return temp;
```
expected:
```typescript
const temp = 2 + a
return 1 + temp;
```

config, with lazyvim
```lua 
  {
    "ThePrimeagen/refactoring.nvim",
    opts = {},
    config = function(_, opts)
      local refactoring = require("refactoring")
      -- local map = require("user.util").map

      refactoring.setup(opts)

      vim.keymap.set({ "v", "n" }, "<leader>rr", refactoring.select_refactor, { noremap = true })
      -- vim.keymap.set("n", "s", require("substitute").operator, { noremap = true })
    end,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
  },

```

**Comment by TheLeoP** [comment]
[This comment](https://github.com/ThePrimeagen/refactoring.nvim/issues/404#issuecomment-1643769956) on #404 contains info about this behaviour

**Comment by TheLeoP** [comment]
I was working in this feature on [this branch[(https://github.com/theleop/refactoring.nvim/tree/better_119), but I'm starting to think that this simply does not make sense at a treesitter level.

Treesitter creates an AST of some piece of code, in this case for `const temp = 1+2+a`:

```treesitter
lexical_declaration [0, 0] - [0, 23]
  variable_declarator [0, 6] - [0, 22]
    name: identifier [0, 6] - [0, 10]
    value: binary_expression [0, 13] - [0, 22]
      left: binary_expression [0, 13] - [0, 18]
        left: number [0, 13] - [0, 14]
        right: number [0, 17] - [0, 18]
      right: identifier [0, 21] - [0, 22]
```

You can see that there are two `binary_expressions`, the first one contains the nodes `identifier` and `binary_expression`, the second one contains two `number` nodes. This means that, the expression looks like:

```
             +---+
         +---| + |---+
         |   +---+   |
       +---+       +---+
   +---| + |---+   | a |
   |   +---+   |   +---+
 +---+       +---+      
 | 1 |       | 2 |      
 +---+       +---+      
```

As you can see, there is no expression `2 + a` as far as the AST is concerned, the smallest node containing both nodes is indeed `1 + 2 + a`. If we were to evaluate the AST, we could conclude that, since the operation been used is an addition, it does not matter if we select on ly the `2 + a` part. But, we can't know this without evaluating the content of the tree first (this is more obvious when changing the operator from `+` to `/`, where extractin some arbitrary part of the code like this may change how the expression gets interpreted by the language.

But, if you were to change the expression to `1 + (2 + a)`, suddenly the representation of the AST changes and there is a expression `2 + a` that can be extracted to a variable.

So, I'm closing this issue and marking it as `wontfix` (sorry, I was the first one looking to have this feature implemented).

**Comment by tuanbass** [comment]
> 

Thanks for the explanation. Technically I agree, it will be dangerous if we try to extract the subtree by any mean.
At least, now I know a workaround (using `()` before extract variable)
