### ISSUE TITLE
Bug: wrong inlining lua variables that are fields 

### ISSUE THREAD

**Issue by chrisgrieser** [ThePrimeagen/refactoring.nvim#463]
Given this lua code:

```lua
-- [] is the cursor position
local function hello()
	local [b]o = vim.bo
	local ft = bo.filetype
	local other_ft = vim.bo.filetype
end
```

Running `:Refactor inline_var` results in this:
```lua
local function hello()
	m.bo -- <-- leftover?
	local ft = vim.bo.filetype
	local other_ft = vim.vim.bo.filetype -- <-- duplicate `vim`
end
```

---

For comparison, inlining the equivalent in javascript works correctly:

```js
// [] is the cursor position
const vim = { bo: { filetype: "js" } };
function hello() {
	const [b]o = vim.bo;
	const ft = bo.filetype;
	const other_ft = vim.bo.filetype;
}
```

results correctly in:
```lua
const vim = { bo: { filetype: "js" } };
function hello() {

	const ft = vim.bo.filetype;
	const other_ft = vim.bo.filetype;
}
```

**Comment by TheLeoP** [comment]
The problem is that we are using the [locals.lua](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/lua/locals.scm) captures and treesitter to find the references to the variable to inline:

https://github.com/ThePrimeagen/refactoring.nvim/blob/7533948b65860ef20292c617bb4faebfb6518363/lua/refactoring/refactor/123.lua#L99-L100

and in both lua and javascript references are defined as `(identifier)`. But, in lua the `bo` in `vim.bo` is an `(identifier)`, while in javascript it's a `(property_identifier)`, so the code above returns 3 references (2 reals and a false positive) for your lua example and 2 references (all real) for your javascript example.

I'll can't think of a trivial (language agnostic) way of distinguishing real references from false positives in this kind of cases.

**Comment by TheLeoP** [comment]
@chrisgrieser could you confirm that #465 fixes the issue?

**Comment by chrisgrieser** [comment]
can confirm, issue is fixed. thank you!
